- app/templates/components/datafruits-chat.hbs
so it doesn't pretend it knows what i want to say
:partybug:
> Turn off autocomplete in the chat input

- app/components/datafruits-player.js
- app/components/datafruits-visuals.js
- app/styles/app.scss
- app/templates/application.hbs
- app/templates/components/datafruits-visuals.hbs
- tests/integration/components/datafruits-visuals-test.js
poll the streampusher api to turn VJ on/off
> Vj updates

- app/components/datafruits-visuals.js
- app/templates/components/datafruits-visuals.hbs
cobbled together from this
https://github.com/agustinaliagac/youtube-live-stream-checker/blob/master/example.html
> use youtube api to check if stream is live, then set the ytid

- .travis.yml
This is the current LTS release series for node.js: https://github.com/nodejs/LTS
> Test on node 6

- package.json
Closes #50
https://greenkeeper.io/
> chore(package): update ember-cli-moment-shim to version 3.0.3

- app/components/datafruits-player.js
- app/components/datafruits-visuals.js
- app/styles/app.scss
- app/templates/components/datafruits-visuals.hbs
- config/environment.js
- package.json
- yarn.lock
https://github.com/ant-media/Ant-Media-Server
> use snailzone vid server

- app/index.html
- app/styles/app.scss
- app/templates/application.hbs
- bower.json
- package.json
> Remove bourbon

- app/templates/home.hbs
How else will everyone know how to behave themselves?
> add Code of Conduct to header

- app/components/datafruits-player.js
- app/components/timetable-loader.js
- app/styles/app.scss
- app/styles/player.scss
- app/styles/stripe-animation.scss
- app/templates/components/datafruits-player.hbs
> use input range for new progress bar

- app/adapters/podcast.js
- app/components/podcast-track.js
- app/components/podcasts-loader.js
- app/routes/home/index.js
- app/templates/components/chat-message.hbs
These were the easiest lint issues to fix right off the bat ⚾ Mostly removing unused variables
> [lint] Removing unused variables

- app/services/chat.js
> use presence in chat service

- app/locales/en/translations.js
- app/locales/ja/translations.js
- app/locales/kr/translations.js
- app/routes/home/about.js
- app/styles/app.scss
- app/templates/home/about.hbs
> thank your patrons

- app/components/datafruits-player.js
- app/styles/app.scss
- app/styles/player.scss
- app/templates/components/datafruits-player.hbs
- app/templates/home.hbs
>  fix radio bar layout

- app/components/datafruits-player.js
- app/services/chat.js
- app/services/metadata.js
- app/services/socket.js
- tests/unit/services/metadata-test.js
- tests/unit/services/socket-test.js
* moved socket connection to its own service. multiple channels can share the same socket, so there is no need to make two websocket connections.
> add service to get metadata from websocket

- app/components/datafruits-chat-input-message.js
- app/styles/app.scss
> better emoji picker

- fastboot_server/server.js
https://github.com/ember-fastboot/fastboot-app-server#pre-and-post-fastboot-middleware-hooks
> set cache-control headers for fastboot server

- app/components/chat-messages.js
- app/components/giphy-search.js
- app/components/podcasts-search.js
- app/initializers/bugsnag.js
- app/models/blog-post-body.js
- app/router.js
- app/serializers/gif.js
- config/dotenv.js
- fastboot_server/server.js
Looks like there are a couple small remaining linting issues to fix. I'll try to knock them out.
> some linting fixes

- app/templates/components/datafruits-chat.hbs
- tests/integration/components/datafruits-chat-test.js
> Images are off

- app/locales/es/translations.js
Not everything here is perfect, but hey it's a start.
> Add Spanish translation

- app/components/datafruits-player.js
- app/locales/en/translations.js
- app/templates/components/container/datafruits-player.hbs
- app/templates/components/datafruits-player.hbs
Fixes #287
Let me know if this is the kind of fix you imagined. I'm not 100% sure how the player works or if this was working right as the live streamer just signed off after I started working on this hahaaaaaa. But in theory if the code comments are to be believed this may handle it.
> Player has 'stop' button while live

- app/components/podcasts-search.js
- app/templates/components/podcasts-search.hbs
> Disable submit on pressing enter

- package.json
- yarn.lock
for https://github.com/datafruits/datafruits/issues/423
> remove ember-cli-pagination

- .dependabot/config.yml
#407 
Runs dependabot monthly, except for security updates which are immediate.
> Reduce dependabot noise

- app/router.js
- package.json
- yarn.lock
Honestly I haven't checked the page views in such a long time, so I guess
it really isn't that important to me.
I've explored using alternatives to google for analytics, but given that
I haven't even checked pageviews maybe its not even worth it.
For now I'd like to at least remove the metrics so google isn't tracking
anyone.
> remove metrics

- app/adapters/application.js
- app/components/blog-post-preview.js
- app/components/blog-post.js
- app/components/chat-message.js
- app/components/datafruits-chat.js
- app/components/datafruits-player.js
- app/components/datafruits-visuals.js
- app/components/timetable-loader.js
- app/controllers/home/chat.js
- app/models/blog-post-body.js
- app/models/blog-post.js
- app/routes/home.js
- app/services/video-stream.js
- package.json
- yarn.lock
Fix the issues introduced by the new version of ember-eslint that we saw in  @caassandra 's PR: https://github.com/datafruits/datafruits/pull/442/files#file-app-components-chat-message-js-L10
> fix some linting issues for new version of ember eslint

- app/components/gif-preview.hbs
- app/components/gif-preview.js
- app/serializers/gif.js
- app/templates/components/giphy-search.hbs
- tests/integration/components/gif-preview-test.js
extract gif preview component
continuation of
https://github.com/datafruits/datafruits/pull/409
> increase gif preview size

- config/ember-intl.js
- translations/en.json
Reverts datafruits/datafruits#477
> Revert "remove duplicate en locale"

- ember-cli-build.js
Possible fix for https://github.com/datafruits/datafruits/issues/448
http://ember-service-worker.com/documentation/configuration/#versioning
> use every-build strategy for ember-service-worker

- app/components/datafruits-player.js
- app/services/video-stream.js
- app/templates/components/datafruits-visuals.hbs
Reverts datafruits/datafruits#508
> Revert "play video's audio temporarily for an event"

- config/environment.js
Hopefully this gets source maps working on rollbar. https://github.com/Exelord/ember-rollbar-client#configuration
> update rollbar config to support code version and sourcemaps

- LICENSE
https://git.pixie.town/thufie/CNPL
resolves #430
> add the Cooperative Non-Violent Public License

- app/templates/components/datafruits-player.hbs
woops https://github.com/datafruits/datafruits/pull/473/files#diff-20c8922dd546afcf7844fe144cc2348cf28a4cda49371d092889ea2f14ca27b9R62
> call correct action to hide vol control

- app/templates/home/coc.hbs
sorry its such a big dumb diff, but its mostly because everything is inside of a div now
> add margin and text alignment to CoC page

- app/components/chat-message.js
- app/templates/components/chat-message.hbs
My attempt at doing https://github.com/datafruits/datafruits/issues/521 Let me know I should change anything : )
> Add dj link from chat

- app/models/microtext.js
- app/templates/components/add-datafruit.hbs
- translations/en.json
fixes this problem with the datafruits
> Fix avatar locale issue

- app/controllers/home/chat.js
This should keep users logged in longer, I noticced you get logged out pretty quickly. Not fully tested though...
> increase cookie expire time

- app/templates/components/container/datafruits-player.hbs
- app/templates/components/datafruits-player.hbs
- app/templates/components/pc-nav.hbs
Reverts datafruits/datafruits#591
> Revert "fix mouseEnter/mouseLeave dep. warnings"

- app/components/add-datafruit.js
- app/components/datafruits-visuals.js
- app/components/pixi.js
- app/controllers/home.js
- app/services/video-stream.js
- tests/acceptance/chat-test.js
> Acceptance testing

- app/services/chat.js
- tests/unit/services/chat-test.js
[ticket](https://github.com/datafruits/datafruits/issues/622)
> Remove log in/out messages from chat

- app/styles/app.scss
> use salmon color as text highlight color

- app/session-stores/application.js
> add cookie session store

- Procfile
- ecosystem.config.js
- package.json
- yarn.lock
This guy sucks. More and more people are saying this.
> kill the purple guy

- app/components/datafruits-chat-input-message.js
This also broke emoji matching recently oops.
> fix matching joined users

- app/components/sign-up/form.js
- app/routes/home.js
- app/routes/home/chat.js
- app/services/chat.js
- app/services/current-user.js
- mirage/config.js
- tests/acceptance/user-settings-test.js
I can't remember why I added this to be honest. It seems to be causing
issues that sometimes redirect someone to the home page from the chat.
> remove authentication from chat route

- app/tailwind/config.js
- app/templates/home/show.hbs
> fix show title

- package.json
- tests/test-helper.js
- yarn.lock
I don't think we need this anymore.
> remove ember-cli-sinon

- .eslintrc.js
- .netlifyredirects
- ember-cli-build.js
- package.json
- urlFinder.js
- yarn.lock
https://github.com/datafruits/datafruits/issues/615#issue-813430550
Looks like the static html will be rendered if you just run `ember build --environment=production`.
> try preember

- app/components/locale-selector.js
- translations/cn.json
Thanks to hojo !
Co-authored-by: hojo <huangshenwei@gmail.com>
> add chinese language

- app/models/dj.js
- app/templates/home/dj.hbs
Show user style, change some fonts to cursive to look more like the show pages
> Update dj pages

- app/components/pixi.js
https://user-images.githubusercontent.com/66243/126410945-9100caef-1b44-4e1e-a96c-b3e02134f4d3.mp4
> start playing sprite animation on random frame

- app/components/chat/username.hbs
- app/components/chat/username.js
- app/components/datafruits-chat-input-message.js
- app/components/user-list-item.js
- app/controllers/home/chat.js
- app/models/dj.js
- app/models/user.js
- app/templates/components/chat-message.hbs
- app/templates/components/pc-nav.hbs
- app/templates/components/user-list-item.hbs
- app/templates/home/user/settings.hbs
- tests/integration/components/chat/username-test.js
- translations/en.json
- translations/ja.json
- translations/ko.json
pronouns / style etc 
depends on https://github.com/datafruits/hotdog_lounge/pull/22
https://github.com/datafruits/streampusher-api/pull/124
> show user info on popup (and add pronouns field)

- app/templates/components/pc-nav.hbs
- app/templates/components/sp-nav.hbs
- translations/en.json
fixes https://github.com/datafruits/datafruits/issues/586
> rename blog to upcoming

- app/helpers/random-loading-message.js
* remove old studio phone msg
* add viz msg
any more ideas to add?
> Fix loading msgs

- app/components/fruit-tip.hbs
- app/components/fruit-tip.js
- app/components/fruit-tip/fruit.hbs
- app/components/fruit-tip/fruit.js
- app/services/chat.js
- tests/integration/components/fruit-tip/fruit-test.js
> show fruit counts

- app/components/pixi.js
adapted this code https://codepen.io/jh3y/pen/VdMBaR
> add snow to pixi.js

- app/components/datafruits-chat.hbs
- app/components/datafruits-chat.js
- tests/integration/components/datafruits-chat-test.js
> fix joining the chat by pressing enter

- app/components/pixi.js
I used this diff on this commit to figure out what was using the snowing animation https://github.com/datafruits/datafruits/commit/05836557076208f276ed1e6acb0ec5480806b13f
> weatherman says it stopped snowing

- app/styles/app.scss
- app/templates/home.hbs
> april of fool

- app/styles/app.scss
- app/templates/home.hbs
> secret grumby

- app/services/current-user.js
> mark user as tracked in current user service

- app/components/datafruits-chat-input-message.ts
- app/components/podcast-track.js
- app/emojiStrategy.ts
- app/initializers/custom-emoji.js
- package.json
- pnpm-lock.yaml
- types/emojione/index.d.ts
Currently when you click an emoji in the selector it will replace the entire message.
This changes it to append to the message instead.
Also converting this component to TS.
> Append emojis instead of replacing entire message

- app/components/datafruits-player.hbs
- app/components/datafruits-player.js
> show Current playing time on archive playback

- app/components/datafruits-player.hbs
- app/components/datafruits-player.js
> fix the return to live stream link when playing podcast

- app/components/sp-nav.hbs
- package.json
- pnpm-lock.yaml
to fix mobile menu not closing bug
> give up and use ember-link-action

- app/components/chat-message.hbs
- app/components/chat/username.hbs
don't show username popup in chat area, only user list
> adjust username popup position

- app/styles/app.scss
- app/templates/home.hbs
- translations/en.json
> add hidden 'skip to main content' link for accessibility

- app/components/podcast-track.js
- app/services/chat.ts
related PRs:
https://github.com/datafruits/hotdog_lounge/pull/28
> track podcast play in redis via hotdog lounge

- app/components/pixi.js
https://www.youtube.com/watch?v=uI6pY_GBok8
Reverts datafruits/datafruits#838
> WEATHERMAN PREDICTS MASSIVE SNOW GLOBS - REPENT TO YOUR WEATHER LORDS!!

- app/components/pixi.js
Is it time to stop the snow blobs????
Reverts datafruits/datafruits#1013
> Revert "WEATHERMAN PREDICTS MASSIVE SNOW GLOBS - REPENT TO YOUR WEATHER LORDS!!"

- app/components/chat-message.hbs
- app/services/chat.ts
We probably want to change the actual highlighting color when you're mentioned, but here's what I got so far; Uses the chat service to see if the message has your username in it, adds a property to the message, and then the template picks up on that and styles the element if it has the @
#1015
> Highlight chat messages that mention your @username

- app/styles/app.scss
- app/templates/home/about.hbs
- config/icons.js
- translations/en.json
forgot about including tiktok in the social media links. also thought it would be cool to have an animation when hovering over them
> add tiktok and color-changing hover effect

- app/components/fruits-affinity.ts
NGL this was a struggle, but LMK if you want me to try out anything else 😎 📊
> update style of affinity chart

- app/components/user-list-item.js
- app/templates/home/dj.hbs
on user pages and chatroom userlist
> fix showing default avatars

- app/components/login-modal.hbs
- app/components/pc-nav.hbs
remove new.gif from sign up link
> add new.gif to forum and wiki

- app/components/chat/emoji-selector.hbs
- app/components/chat/enable-gifs-button.hbs
- app/components/emoji-selector/emoji.hbs
- app/components/giphy-search.hbs
- app/styles/app.scss
this fixes a few presentational things in the chat like the buttons and the emoji selector. the biggest thing was making the dialog a little wider. I thought cabbage should be more visible when the fruit tip menu is open.
> Fix chat button spacing

- app/helpers/format-day.js
- app/models/dj.js
- app/models/user.js
- app/templates/home/dj.hbs
- translations/en.json
- translations/ja.json
- translations/ko.json
> show created at/last login on profiles

- app/components/add-datafruit.hbs
- app/components/add-datafruit.js
- app/models/microtext.js
> add the timestamp to the micro texts

- app/components/hack-button.hbs
- app/components/hack-button.ts
- app/styles/app.scss
- app/templates/home.hbs
- translations/en.json
It just leads to the github. Thought it might be a way to encourage people to get involved on the code.
Also added this box-shadow to the buttons. I can remove it if anyone isn't into it.
> add hack button

- app/components/chat/input-message.ts
woops, with the new event handler, you can't paste anything else in the input other than an image. this fixes it and handles both
> check if there's any files in the clipboard data

- app/models/scheduled-show.js
- app/templates/home/show.hbs
do all markdown rendering on frontend to keep consistent
> stop using htmlDescription

- app/components/fruit-tip/fruit.ts
resolves https://github.com/datafruits/datafruits/issues/1126
> fix fruit tip disabled for non-logged in user

- app/components/pc-nav.hbs
- app/components/ui/modal.ts
- app/components/user-notification.hbs
- app/components/user-notification.ts
- app/components/user/notifications-window.hbs
- app/components/user/notifications-window.ts
- app/models/user.js
- app/styles/app.scss
- app/styles/shake.scss
- app/templates/home.hbs
- tests/integration/components/user/notifications-window-test.ts
- types/glint.d.ts
closes https://github.com/datafruits/datafruits/issues/1123
https://github.com/datafruits/datafruits/assets/66243/94eabe0d-5603-4fd5-8346-38b0fc0a3a4d
> shakey pidgeon

- .projections.json
Sorry for adding a vim specific file in the repo but I think I'll keep it in repo until I'm confident enough with how it works to fold it into my main editor config.
> add .projections.json for vim-projectionist

- app/components/hack-button.hbs
- translations/en.json
This reverts commit 6ab0c431845f68a983fca84a84012105a28daa63.
> Revert "link hack button to expo for now"

- app/components/gift-user-fruit-tix.ts
- tests/integration/components/gift-user-fruit-tix-test.ts
> reload currentUser after fruit tix gift

- app/components/my-shows/episode-form.hbs
- app/components/my-shows/episode-form.ts
- app/components/my-shows/recordings-search.ts
- app/models/scheduled-show.js
using prerecord file as archive publish
> add a checkbox for

- app/controllers/home/user/settings.js
- app/templates/home/user/settings.hbs
- translations/en.json
- translations/ja.json
- add username to user settings form
- add more greetings
- add more hellos
- fix translation and margin
- add ja locale
> add username locale

- app/components/user/show-form.hbs
- app/models/show-series.ts
- use helper for input date value
- remove unneeded dayjs import
> fix input date thingy

- app/templates/home/shows/episode.hbs
> make link to other shows in series bigger

- app/components/podcasts.hbs
not really happy with this hack but it will do for now
> check if track exists before rendering podcast track

- app/components/my-shows/episode-form.hbs
- translations/en.json
- translations/ja.json
> add mixcloud/soundcloud links to episode form

- app/components/pixi.js
Reverts datafruits/datafruits#1020
⛄ ⛄
> Revert "Revert "WEATHERMAN PREDICTS MASSIVE SNOW GLOBS - REPENT TO YOUR WEATHER LORDS!!""

- app/components/locale-selector.hbs
not sure why this if/else approach works instead of setting selected, but this fixes #1169
> fix locale selector issue

- app/components/emoji-selector/emoji.hbs
- app/components/emoji-selector/emoji.js
- store emoji size pref in cookie
- animation on emoji click
> emoji selector click anim

- app/components/pixi.js
destroy and recreate app to try to fix memory leak
> refactor pixi re-init

- app/helpers/random-loading-message.js
> add more random loading messages

- app/components/weather-selector.hbs
- app/components/weather-selector.js
- app/services/weather.ts
https://weatherishappening.network/@WEATHERISHAPPENING/111715704504092523
> weatherman reports only 0.5 inch of foolish white stuff

- app/components/add-datafruit.hbs
- app/components/blog-post.hbs
- app/components/container/datafruits-player.hbs
- app/components/gift-user-fruit-tix.hbs
- app/components/post.hbs
- app/components/validated-field.hbs
- app/components/wiki/form.hbs
- app/templates/container/show.hbs
- app/templates/head.hbs
- app/templates/home/user/settings.hbs
https://github.com/ember-codemods/ember-no-implicit-this-codemod
> run no implicit this codemod

- app/components/track-uploader.ts
use uploadBinary so form data is not mixed in to file
> fix track upload

- app/components/datafruits-player.hbs
- app/components/datafruits-player.ts
I'll fix the tests, but this adds finer control for the volume, shows the percentage, and hides itself 500ms later than usual
any thoughts on what the style should be for the percentage?
not sure how to fix this test from my end
https://github.com/datafruits/datafruits/actions/runs/10362883763/job/28685609298?pr=1360#step:11:52
> finer volume control

- app/components/podcast-track.hbs
- app/controllers/home/shows/episode.ts
- app/lib/type-utils.ts
- app/models/scheduled-show.js
- app/templates/home/shows/episode.hbs
> refactor episode edit permission

- app/components/shrimpo/voting-categories-table.hbs
- app/components/shrimpo/voting-categories-table.ts
- app/components/time-picker.ts
- translations/en.json
- **fix issue updating episode time**
- **reload shrimpo after voting**
> refresh voting percent completion

- app/components/shrimpo/entry-card.hbs
- app/components/shrimpo/entry-card.ts
- app/components/shrimpo/form.hbs
- app/components/shrimpo/form.ts
- app/components/shrimpo/voting-categories-table.hbs
- app/models/shrimpo-entry.ts
- app/models/shrimpo-voting-category-score.ts
- app/models/shrimpo-voting-category.ts
- app/templates/home/shrimpos/show.hbs
- translations/en.json
- **mega shrimpo form**
- **add more already voted ui**
> mega shrimpo ui

- app/components/shrimpo/entry-uploader.hbs
- app/components/shrimpo/entry-uploader.ts
- app/models/shrimpo.ts
- **allow multiple entries on shrimpo**
- **check multi flag**
> shrimpo multi entry

- app/models/shrimpo-entry.ts
- app/models/shrimpo-voting-category-score.ts
- app/templates/home/shrimpos/entries/show.hbs
- **add inverses to relationships**
- **show score cat emoji, some formatting**
> shrimpo mega fixes

- app/components/chat-lazy-image.hbs
> set limit on image height
