datafruits/datafruits

- app/components/chat-lazy-image.js
- app/components/chat-message.js
- app/components/podcasts-search.js
- app/templates/components/chat-lazy-image.hbs
- app/templates/components/chat-message.hbs
- tests/integration/components/chat-lazy-image-test.js
I extended the component from the lazy image addon, added an observer
to fire when the 'loaded' property is set to true.
The addon sets this property to true using an onload listener on the img
tag.
> fix scrolling the chat when an image has loaded

- ember-cli-build.js
This will speed builds up. You won't be able to see linting errors in
the server console anymore, but I have my editor configured to show them
anyway and they are also ran on CI, so its not really necessary to run
them on every build I think.
> disable linting in the build

- app/styles/calendar.scss
- app/templates/components/timetable-calendar.hbs
Resolves #224 with some css overflow and adds a title so the full text can be accessed via hover of other A11y methods.
---
Allowed inline-styles in the template lint since ember-calendar appears to rely on it and that isn't changing anytime soon since that addon appears to be abandoned. Now this component's template file passes template linting.
> Truncate text on calendar

- app/locales/en/translations.js
- app/styles/app.scss
- app/templates/components/blog-post-preview.hbs
- app/templates/components/container/datafruits-player.hbs
- app/templates/components/datafruits-chat-input-message.hbs
- app/templates/components/datafruits-chat.hbs
- app/templates/components/datafruits-player.hbs
- app/templates/components/datafruits-visuals.hbs
- app/templates/components/giphy-loader.hbs
- app/templates/components/giphy-search.hbs
- app/templates/components/pc-nav.hbs
- app/templates/components/podcast-track.hbs
- app/templates/components/podcasts-search.hbs
- app/templates/components/sp-nav.hbs
- app/templates/components/tweet-button.hbs
- app/templates/container/index.hbs
- app/templates/container/show.hbs
- app/templates/home.hbs
- app/templates/home/about.hbs
- app/templates/home/chat.hbs
- app/templates/home/coc.hbs
- app/templates/home/dj-inquiry.hbs
- app/templates/home/dj.hbs
- app/templates/home/djs.hbs
- app/templates/home/index.hbs
- app/templates/home/loading.hbs
- app/templates/home/podcasts.hbs
- app/templates/home/show.hbs
- app/templates/home/subscribe.hbs
- app/templates/not-found.hbs
Assisting in getting closer to green builds again <3
```bash
yarn lint:hbs
```
---
This touches a ton of files. The best things to QA are localized text strings because while I did try to be careful, I did move well over a hundred bits of localized text by hand to the english translations file. Look for "Missing loc" or whatever it says throughout the site - especially on text heavy pages like CoC and About.
> Fixed all template linting issues

- app/services/video-stream.js
I tried to accomplish this with tracked properties in https://github.com/datafruits/datafruits/pull/413,
but I couldn't get it to work so I am doing it just using `set` here.
> teardown player on retryplaylist event

- app/components/datafruits-player.js
- app/templates/components/datafruits-player.hbs
Its set pretty high to delay hiding the control (2500 ms) but I think I
like this way, seems much easier to use.
Still needs to be fixed on mobile/touch devices....
> debounce hiding vol control

- app/templates/components/datafruits-visuals.hbs
Closes #496 
I don't know if this is actually the problem with the video, but it gets rid of the error message. Looking at the [source code](https://github.com/videojs/video.js/blob/master/src/js/player.js#L4668-L4716), there's this part:
```js
if (Dom.hasClass(tag, 'vjs-fluid')) {
tagOptions.fluid = true;
}
```
Since all we were doing was trying to set `tagOptions.fluid` to `true` anyway, I just got rid of the `data-setup` tag entirely and applied the `vjs-fluid` class. I decided not to bother with trying to put valid json inside an html attribute, because i suspect that would be a headache.
> Fix issue with videojs

- app/models/scheduled-show.js
- app/templates/home/dj.hbs
- app/templates/home/show.hbs
Trying to cut down on async requests.
> use hostedBy string field for dj, instead of just loading the whole resource

- app/templates/components/chat-message.hbs
Deprecation warning for `ember-composable-helpers`
> change contains to include helper

- app/templates/home.hbs
i think it looks a little better have the datafruits-ticker moved the absolute bottom, below the player, and the rest of the controls 📈📉📊🍇
> move datafruits to the bottom

- app/templates/components/podcast-track.hbs
add some space between the labels, adjust text style etc.
> Fix track labels style

- app/templates/home.hbs
* hide theme selector on mobile
* fix hiding desktop logo on mobile
I'd like to add a "site settings" page somewhere, to allow mobile users to select language and theme. More settings/options can be moved there in the future if its crowding up the mobile view too much.
Next I'd like to clean up the chat login section at the bottom on mobile as its way too crowded, perhaps adding another modal.
> fix some mobile display issues

- app/templates/components/pc-nav.hbs
- app/templates/components/sp-nav.hbs
While the new cooltrash.shop is under construction, change the shop link to the bandcamp merch page, there are at least a few items there.
> replace cooltrash link with bandcamp merch page for now

- app/components/chat-messages.js
- app/components/datafruits-chat.js
- app/services/chat.js
We relied on the timing of `willRender` before, this no longer exists in new Ember versions.
We switched to a `did-insert` modifier, but by the time that code runs the new message is already inserted, so the way we checked if you were scrolled to the bottom doesn't work.
I am now storing the variable `isScrolledToBottom` in the chat service. It's updated when you scroll the chat.
https://github.com/emberjs/ember-render-modifiers/issues/38#issuecomment-895968119
> fix chat scrolling bug

- app/controllers/home/chat.js
- app/services/chat.js
If they rejoin the chat with an existing token, send the authorize_token
msg to the channel again.
This will ensure the Presences (chat userlist) stays synced on the
Phoenix side.
> authorize user again for chat

- app/components/chat-messages.js
This should make the warnings in chrome/lighthouse go away.
reference: https://web.dev/uses-passive-event-listeners/?utm_source=lighthouse&utm_medium=devtools#how-to-make-event-listeners-passive-to-improve-scrolling-performance
> mark scroll event listeners as passive

- app/components/datafruits-player.js
- app/services/page-title.js
This can help improve the experience on mobile, as your lock screen will
show the page title so you know what you are listening to on datafruits.
> set now playing metadata in page title

- app/components/datafruits-player.js
- app/services/video-stream.js
-  [x] play video's audio if /live is active
> use video's audio when /live viz endpoint is active

- app/templates/home/coc.hbs
- translations/en.json
This links to the google doc on how the CoC is enforced from the main CoC page.
Maybe this can be a wiki article later when we implement the wiki.
> link to coc encforcement doc on coc page

- app/templates/home/about.hbs
- config/icons.js
- translations/en.json
The youtube and discord fa icons were missing and I was able to fix it by adding these names to the icon config. I also modified the subscription section of the about page to include the Ampled graphic. Oh yeah, and I reorganized the icons at the bottom. It seems like we should try to group them by category, but IDK, maybe there's a better way of displaying all of these.
> Missing social media icons in About page

- app/components/chat-message.hbs
- app/components/chat-message.js
- tests/integration/components/chat-message-test.js
here are two big burritos in one bag:
* doesn't show the URL when an image is posted
* handles the data URL format for base 64-encoded images
I tested the data URL handling locally and it worked with one exception. The regex to recognize the format was allowing any data type. I've refined it to handle a few image formats, but haven't tested that change yet
> show data urls and hide text

- app/components/chat/input-message.hbs
- app/components/chat/input-message.ts
ok you can actually copy and paste an image into the chat now. tested in chrome, doesn't work in firefox tho https://developer.mozilla.org/en-US/docs/Web/API/Clipboard/read#browser_compatibility 😢
> set clipboard data to base64 image

- app/components/add-datafruit.hbs
- app/components/datafruits-player.hbs
- app/components/podcast-track.hbs
- app/components/podcasts.hbs
- app/components/sp-nav.hbs
- app/styles/app.scss
- app/styles/player.scss
Wanted to use the site a little easier with my tiny iPhone 5 so I adjusted the style a bit behind media queries
The navigation menu can scroll up an down if the screen is shorter than contents.
I also added a media query to reduce the font size for the now playing text, the podcast archive page, and I added indentation for a cleaner layout in the list of podcasts. No more horizontal scrolling.
thanks for checking out this pull request
Brad
> mobile style tweaks

- app/components/datafruits-player.ts
This reverts commit 9530aa8e21806f968c117f3c79601bea3bb17b82.
I think this is actually kind of annoying since we use spacebar to scroll, or at least I do.
> Revert "play/pause audio with spacebar"

- app/components/chat-settings.hbs
- app/components/chat/color-picker.hbs
- app/components/chat/color-picker.js
- app/components/datafruits-chat.hbs
- app/components/datafruits-chat.js
- app/services/chat-text.js
- app/styles/app.scss
- translations/en.json
carrying on the work from an old branch #412  that adds a color picker that changes the color of the text in the chat room
few things to address:
> change chat text color

- app/components/djs/list.hbs
- app/components/pc-nav.hbs
- app/components/sp-nav.hbs
- app/router.js
when navigating to the fruits page (aka 'djs'), it takes a long time for all possible users to return. Since the route is called 'djs', maybe it should default to users with the DJ role?
Also, there should be pagination because even filtering by DJs takes a long time for the backend to process.
> Get djs by default

- .prettierrc.js
- app/components/labels-select.hbs
- app/components/my-shows/episode-form.hbs
- app/components/my-shows/episode-form.ts
- app/components/my-shows/recording-selector.hbs
- app/components/my-shows/recording-selector.ts
- app/components/track-uploader.hbs
- app/components/track-uploader.ts
- app/helpers/episode-image-url.js
- app/models/scheduled-show.js
- translations/en.json
- translations/es.json
- translations/ja.json
- translations/ko.json
- translations/zh-cn.json
maintaining archives is pretty easy, but there's some visual clunkiness that's making it hard to navigate the form and understand if you should check this box to select or what, so I tried redoing some things to make it look uniform and manageable. 
I'd like the title of the page say "Editing episode of {title}" or something, so I added a little text that says (episode update form). Then we got the air-date, title, description, tags, and artwork
I'd like to have the dashed-border overlayed over the image and the button floating over the bottom-right of it (like the webcam feature noone uses). below the artwork is the new radio group to either Select a recording or Upload a set
Here's the part where I used some AI.  The "Upload a set" shows the file upload
And then there's the Archive …
> cleanup episode form
